### ISSUE TITLE
Cant add the custom notifier at Home Assistant - different virtualbox

### ISSUE THREAD

**Issue by dkamioka** [noeRls/timebox-home-assistant#1]
Hi, first of all, thanks a lot for doing this! This is for whoever like me spent hours trying to make this work with this setup:

1) Using Virtualbox image from Home Assistant website 
2) Because the Home Assistant OS is specific, it's not a regular linux that we can log in and run docker, etc I needed to run another virtualbox with a regular linux, then ran the docker as the documentation guides
3) Then I had to make my Home Assistant connect to a different IP address on the port 5555

I was receiving error on loading the notify.timebox I fixed it by editing the file \custom_components\timebox\notify.py and setting the TIMEOUT = 15 (it was 5 and was giving me timeout) try larger numbers if you are also having this problem.

Bye and thanks again!

The error on the logs of the home assistant:
---------------------------------------

Logger: homeassistant.components.notify
Source: custom_components/timebox/notify.py:116
Integration: Notifications (documentation, issues)
First occurred: 2:43:35 AM (1 occurrences)
Last logged: 2:43:35 AM

Error setting up platform timebox
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.15.13', port=5555): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 301, in async_setup_platform
    notify_service = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/timebox/notify.py", line 51, in get_service
    if not timebox.isConnected():
  File "/config/custom_components/timebox/notify.py", line 133, in isConnected
    return self.send_request('Failed to connect to the timebox', '/connect', data={"mac": self.mac})
  File "/config/custom_components/timebox/notify.py", line 116, in send_request
    r = requests.post(f'{self.url}{url}', data=data, files=files, timeout=TIMEOUT)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.15.13', port=5555): Read timed out. (read timeout=5)

**Comment by noeRls** [comment]
Hi, thanks for spending time troubleshooting your issue, I am sure it will be helpful for others. I have updated the timeout to 15.

I am glad you get it working!
